#!/bin/sh
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-update".
unset $(git rev-parse --local-env-vars)
cd /var/www/html/git && git pull origin master
